Run local container 2
equinor/data-modelling-tool pull request #1077
Opened 2022-03-21 12:08 UTC by KristianKjerstad

## What does this pull request change?

## Why is this pull request needed?

## Issues related to this change:

## Checklist

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved terminology
- [ ] You have added types and interfaces where possible
- [ ] You have added tests
- [ ] You have updated documentation
- [ ] You use defined architecture principles and project structures
- [ ] You are happy with the code quality

2022-03-22 15:39 UTC, KristianKjerstad commented on api/src/home/DMT/data/demoDSAlias/DMT-demo/Plugins/Form/SingleFieldExample.json
> -  "_id": "SingleFieldExample",
this caused an uid error on reset-app

2022-03-22 15:43 UTC, KristianKjerstad commented on api/src/home/workflow/job_handlers/local_container/__init__.py
> +                raise Exception("Cannot have any spaces in the applicationInput for local container job")
there was a strange bug here - if the json string contains any spaces at all, the container fails... 
There probably is a better way to deal with this.

2022-03-28 12:13 UTC, soofstad commented on api/src/home/analysis-platform/data/AnalysisPlatformDS/Blueprints/SIMAApplicationInput.json
> +    }
Think this should be flattened. As it is now optional, and will make things a bit easier

2022-03-28 12:33 UTC, soofstad requested changes

2022-03-28 12:33 UTC, soofstad commented on api/src/home/workflow/data/WorkflowDS/Blueprints/Job.json
> +      "attributeType": "AnalysisPlatformDS/Blueprints/SIMAApplicationInput",
This should be reverted. Job is a generic construct

2022-03-28 12:33 UTC, soofstad commented on api/src/home/workflow/data/WorkflowDS/Blueprints/Task.json
> +      "type": "AnalysisPlatformDS/Blueprints/SIMAApplicationInput",
Same. type: "object"

2022-03-28 12:33 UTC, soofstad commented on local-container/Dockerfile
> +    pip install poetry && \
replace old  "sre-wrapper" with this "local-container". Keep old name

2022-03-28 12:33 UTC, soofstad commented on local-container/wrapper.py
> +@click.option("--result-link-target", help="dotted id to the operation entity's results list. Should be on the format: entityId.x.simulationConfigs.y.results", type=str, required=True)
These should also be a part of "application-input"

2022-03-28 12:33 UTC, soofstad commented on web/packages/plugins/apps/analysis-platform/src/modules/Analysis/components/AnalysisCard.tsx
> +              saveAndStartLocalContainerJob(task)
should just be "job", not a type of job

2022-03-28 12:33 UTC, soofstad commented on web/packages/plugins/ui/job-handlers/src/index.tsx
> +import { EditLocalContainer } from './EditLocalContainer'
I think these could use the same component. Only needed attribute is "image"

2022-03-29 08:15 UTC, soofstad approved these changes

2022-03-29 08:15 UTC, soofstad commented on web/packages/plugins/apps/analysis-platform/src/modules/Analysis/components/AnalysisCard.tsx
> +        const containerJob: TJob = {
```suggestion
        const job: TJob = {
```
It can be any type of job

2022-03-29 08:33 UTC, merged