add DestinationPicker to EditTask.tsx, and update NewEntityButton.tsx functionality
equinor/data-modelling-tool pull request #1272
Opened 2022-06-15 09:09 UTC by KristianKjerstad

## What does this pull request change?

## Why is this pull request needed?

## Issues related to this change
closes #1271

2022-06-15 13:16 UTC, netr0m approved these changes
Looks good!

2022-06-15 18:33 UTC, soofstad requested changes
Nice! But the requested feature was to hide the "blueprint" and "destination" pickers if the values are passed to the component.
The goal is to remove as much clutter as possible for "basic users"

2022-06-21 06:28 UTC, soofstad approved these changes

2022-06-21 06:28 UTC, soofstad commented on web/packages/plugins/shared/common/src/components/NewEntityButton.tsx
> +          {!!!type && (
Why is `!type` not enough? :o

2022-06-27 07:11 UTC, merged