have create entity work again
equinor/data-modelling-tool pull request #1323
Opened 2022-07-13 12:34 UTC by soofstad

## What does this pull request change?
- Rework and fix "CreateEntity"

## Why is this pull request needed?
- CreateEntity did not properly create entities

## Issues related to this change
closes #1322

2022-07-25 09:07 UTC, KristianKjerstad requested changes
nice!
Just a minor thing about the integer attribute type

2022-08-01 08:13 UTC, netr0m commented on api/src/domain_classes/blueprint.py
>      def get_none_primitive_types(self) -> List[BlueprintAttribute]:
```suggestion
    def get_non_primitive_types(self) -> List[BlueprintAttribute]:
```
None-primitive => non-primitive?

2022-08-01 08:14 UTC, netr0m commented on api/src/services/application_service.py
>          for attr in first.get_none_primitive_types():
```suggestion
        for attr in first.get_non_primitive_types():
```

2022-08-01 08:20 UTC, netr0m commented on api/src/utils/create_application_utils.py
>      for attribute in blueprint.get_none_primitive_types():
```suggestion
    for attribute in blueprint.get_non_primitive_types():
```

2022-08-01 08:23 UTC, netr0m requested changes
Looks good! One remark on naming (None-primitive => non-primitive), plus what Kristian mentioned.

2022-08-08 12:05 UTC, soofstad commented on api/src/tests/unit/instantiate_entity.py
> +            {"attributeType": "integer", "type": "system/SIMOS/BlueprintAttribute", "name": "length"},
Added "integer" back in. Not sure why I removed it...

2022-08-08 13:38 UTC, netr0m commented on api/src/utils/create_entity_utils.py
> +            return 0
Keeping integer after all?

2022-08-08 13:38 UTC, netr0m approved these changes

2022-08-09 06:50 UTC, KristianKjerstad approved these changes

2022-08-10 05:38 UTC, merged