Refactor/add more types 2
equinor/data-modelling-tool pull request #1381
Opened 2022-08-29 07:16 UTC by KristianKjerstad

## What does this pull request change?

## Why is this pull request needed?

## Issues related to this change

2022-09-05 07:08 UTC, netr0m commented on web/packages/plugins/dmt-app/src/pages/SearchPage.tsx
> +        handleSelectedItemsChange={(event) => {
```suggestion
        handleSelectedItemsChange={(event) => {
```
Can/should we include a type here?

2022-09-05 07:10 UTC, netr0m commented on web/packages/plugins/sima-application-input/src/EditSimaApplicationInput.tsx
> +  "Ansole.log('tabData', tabDataalysisPlatformDS/Blueprints/STask"
```suggestion
const STaskBlueprint = "AnalysisPlatformDS/Blueprints/STask"
```
fix typo / accidental paste

2022-09-05 07:11 UTC, netr0m commented on web/packages/plugins/sima-application-input/src/EditSimaApplicationInput.tsx
> +  "Ansole.log('tabData', tabDataalysisPlatformDS/Blueprints/STask"
```suggestion
const STaskBlueprint: string = "AnalysisPlatformDS/Blueprints/STask"
```
fix typo, add type?

2022-09-05 07:13 UTC, netr0m requested changes
See the two inline comments; one for a typo in a variable's value and another for a potentially missing type. Otherwise it looks good!

2022-09-05 07:53 UTC, KristianKjerstad commented on web/packages/plugins/dmt-app/src/pages/SearchPage.tsx
> +      <Autocomplete
MultiSelect from EDS is depreciated. Substituted with the Autocomplete component as recomended by EDS
https://eds-storybook-react.azurewebsites.net/?path=/docs/inputs-select-multiselect--default

2022-09-06 12:19 UTC, netr0m approved these changes

2022-09-08 06:13 UTC, merged